# Generated by Django 4.2.7 on 2023-11-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cached', models.DateField(auto_now_add=True)),
                ('news_data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
