# Generated by Django 4.2.7 on 2023-11-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscall', '0002_cachednews_delete_news_delete_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cached', models.DateField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('news_data', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cachednews',
            name='news_data',
        ),
        migrations.AddField(
            model_name='cachednews',
            name='items',
            field=models.ManyToManyField(to='newscall.cachednewsitem'),
        ),
    ]
