# Generated by Django 4.2.7 on 2023-11-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscall', '0003_cachednewsitem_remove_cachednews_news_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachednews',
            name='items',
        ),
        migrations.AddField(
            model_name='cachednews',
            name='news_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CachedNewsItem',
        ),
    ]
